"""Hard-coded crisis responses. These are NEVER generated by the LLM."""

CRISIS_RESPONSE = (
    "I'm concerned about what you're sharing. Please reach out to the "
    "988 Suicide & Crisis Lifeline (call or text 988) or Crisis Text Line "
    "(text HOME to 741741). They're available 24/7 and can help. "
    "Your care team has been notified."
)

CLINICAL_BOUNDARY_RESPONSE = (
    "I'm not able to provide medical advice, diagnoses, or treatment recommendations. "
    "Please reach out to your care team for clinical guidance. "
    "I'm here to help with your wellness goals and exercise program!"
)

BLOCKED_RESPONSE = (
    "I want to make sure I give you the best support. "
    "Could you rephrase what you'd like help with? "
    "I'm here to assist with your wellness goals and exercise program."
)
